#!/usr/bin/env bash
# ops-cron-competitor-daily.sh — Daily 17:00 roll-up of med-severity competitor signals
#
# Drains queue/daily.jsonl, groups by competitor, writes a markdown roll-up,
# and pushes to Telegram if creds are present.
#
set -euo pipefail

DATA_DIR="${OPS_DATA_DIR:-$HOME/.claude/plugins/data/ops-ops-marketplace}"
LOG_DIR="$DATA_DIR/logs"
LOG="$LOG_DIR/competitor-daily.log"
QUEUE_DIR="$DATA_DIR/competitor_state/queue"
REPORT_DIR="$DATA_DIR/reports/competitor-intel"
PREFS_PATH="$DATA_DIR/preferences.json"

mkdir -p "$LOG_DIR" "$QUEUE_DIR" "$REPORT_DIR"

log() { printf '%s [competitor-daily] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1" | tee -a "$LOG"; }

# ── Credentials ───────────────────────────────────────────────────────────────
TELEGRAM_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
TELEGRAM_CHAT="${TELEGRAM_CHAT_ID:-}"

if [[ -z "$TELEGRAM_TOKEN" ]]; then
  TELEGRAM_TOKEN=$(doppler secrets get TELEGRAM_BOT_TOKEN --plain 2>/dev/null || true)
fi
if [[ -z "$TELEGRAM_CHAT" ]]; then
  TELEGRAM_CHAT=$(doppler secrets get TELEGRAM_CHAT_ID --plain 2>/dev/null || true)
fi

# ── Config ────────────────────────────────────────────────────────────────────
pref_get() {
  local key="$1"
  [[ -f "$PREFS_PATH" ]] || { echo ""; return; }
  jq -r --arg k "$key" '.competitor_intel[$k] // ""' "$PREFS_PATH" 2>/dev/null || echo ""
}

BRAND_NAME="${BRAND_NAME:-$(pref_get brand_name)}"
BRAND_NAME="${BRAND_NAME:-Unknown Brand}"
REPORT_TIMEZONE="${REPORT_TIMEZONE:-$(pref_get report_timezone)}"
REPORT_TIMEZONE="${REPORT_TIMEZONE:-UTC}"

# ── Queue state ───────────────────────────────────────────────────────────────
DAILY_QUEUE="$QUEUE_DIR/daily.jsonl"

if [[ ! -f "$DAILY_QUEUE" ]] || [[ ! -s "$DAILY_QUEUE" ]]; then
  log "HEARTBEAT_OK"
  exit 0
fi

log "Draining daily queue for brand=$BRAND_NAME"

TODAY=$(TZ="$REPORT_TIMEZONE" date '+%Y-%m-%d')
REPORT_FILE="$REPORT_DIR/daily-${TODAY}.md"

# ── Build grouped report ──────────────────────────────────────────────────────
# Collect all events, group by competitor using jq slurp
ALL_EVENTS=$(cat "$DAILY_QUEUE")

EVENT_COUNT=$(printf '%s\n' "$ALL_EVENTS" | grep -c '^{' 2>/dev/null || echo 0)
log "Processing $EVENT_COUNT med-severity event(s)"

# Group by competitor → top 3–5 snippets per competitor
GROUPED=$(printf '%s\n' "$ALL_EVENTS" | jq -s '
  group_by(.competitor)
  | map({
      competitor: .[0].competitor,
      events: (
        sort_by(.timestamp) | reverse
        | .[0:5]
        | map("- [" + (.source // "?") + "] " + (.snippet // "")[0:180])
      )
    })
  | sort_by(.competitor)
' 2>/dev/null || echo "[]")

COMPETITOR_COUNT=$(printf '%s' "$GROUPED" | jq 'length' 2>/dev/null || echo 0)

# ── Write markdown report ─────────────────────────────────────────────────────
{
  printf '# %s Competitor Intel — Daily Roll-up\n' "$BRAND_NAME"
  printf '**Date:** %s  \n' "$(TZ="$REPORT_TIMEZONE" date '+%a %d %b %Y %H:%M %Z')"
  printf '**Signals:** %s med-severity events across %s competitor(s)\n\n' "$EVENT_COUNT" "$COMPETITOR_COUNT"
  printf '---\n\n'

  if [[ "$COMPETITOR_COUNT" -eq 0 ]]; then
    printf '_No med-severity signals in queue._\n'
  else
    printf '%s' "$GROUPED" | jq -r '.[] | "## \(.competitor)\n\n" + (.events | join("\n")) + "\n"' 2>/dev/null || true
  fi

  printf '\n---\n_Generated by ops-cron-competitor-daily.sh at %s_\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$REPORT_FILE"

log "Report written to $REPORT_FILE"

# Update latest symlink
ln -sf "$REPORT_FILE" "$REPORT_DIR/latest-daily.md"

# ── Telegram push ─────────────────────────────────────────────────────────────
if [[ -n "$TELEGRAM_TOKEN" && -n "$TELEGRAM_CHAT" ]]; then
  # Compact Telegram summary (Telegram has 4096-char limit)
  TG_SUMMARY=$(printf '*%s Competitor Daily — %s*\n%s signals, %s competitor(s)\n\n' \
    "$BRAND_NAME" "$TODAY" "$EVENT_COUNT" "$COMPETITOR_COUNT")

  TOP_BULLETS=$(printf '%s' "$GROUPED" | jq -r '
    .[0:5]
    | .[]
    | "• *" + .competitor + "*: " + (.events[0] // "no detail")
  ' 2>/dev/null | head -5 || true)

  TG_TEXT="${TG_SUMMARY}${TOP_BULLETS}"
  TG_TEXT="${TG_TEXT:0:4000}"

  TG_RESP=$(curl -s --max-time 15 -X POST \
    "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
    -H "Content-Type: application/json" \
    -d "$(jq -n --arg chat "$TELEGRAM_CHAT" --arg text "$TG_TEXT" \
        '{chat_id: $chat, text: $text, parse_mode: "Markdown"}')" 2>/dev/null || echo '{"ok":false}')

  if printf '%s' "$TG_RESP" | jq -e '.ok == true' >/dev/null 2>&1; then
    log "Telegram digest sent to chat=$TELEGRAM_CHAT"
  else
    log "WARN: Telegram send failed — report saved to disk only ($REPORT_FILE)"
  fi
else
  log "INFO: Telegram not configured — report saved to disk only ($REPORT_FILE)"
fi

# ── Truncate queue after processing ──────────────────────────────────────────
: > "$DAILY_QUEUE"
log "Daily queue truncated"
log "HEARTBEAT_OK"
